config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post 'import'
    end
  end
  resources :employees
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blogs_controller.rb
require 'csv'
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    # @blogs = current_user.blogs
    @pagy, @blogs = pagy(current_user.blogs)

  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = current_user.blogs.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = current_user.blogs.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    file = params[:attachment]
    batch_size = 1000
    csv_file = file.tempfile
    csv_file.readline

    loop do
      records = []
      batch_size.times do
        line = csv_file.gets&.chomp
        break if line.nil? || line.empty?
        records << line
      end
      break if records.empty?
      ActiveRecord::Base.transaction do
        records.each do |line|
          title, body = line.split(',')
          blog_attributes = { title: title, body: body }
          current_user.blogs.create!(blog_attributes)
        end
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = current_user.blogs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :user_id)
    end
end

app/controllers/concerns/employee_api.rb
# app/controllers/concerns/employee_api.rb
module EmployeeApi
  extend ActiveSupport::Concern

  def fetch_employees_from_api(page = nil)
    uri = build_uri("employees", page)
    send_request(uri)
  end

  def fetch_employee_from_api(id)
    uri = build_uri("employees/#{id}")
    send_request(uri)
  end

  def create_employee_via_api(params)
    uri = build_uri("employees")
    send_http_request(uri, Net::HTTP::Post, params)
  end

  def update_employee_via_api(id, params)
    uri = build_uri("employees/#{id}")
    send_http_request(uri, Net::HTTP::Put, params)
  end

  def delete_employee_via_api(id)
    uri = build_uri("employees/#{id}")
    send_http_request(uri, Net::HTTP::Delete)
  end

  private

  def build_uri(path, page = nil)
    uri = URI("https://dummy-employees-api-8bad748cda19.herokuapp.com/#{path}")
    uri.query = "page=#{page}" if page.present?
    uri
  end

  def send_request(uri)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  end

  def send_http_request(uri, request_type, params = nil)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = (uri.scheme == 'https')

    request = request_type.new(uri.path)
    request['Content-Type'] = 'application/json'
    request.body = params.to_json if params

    http.request(request)
  end
end

app/controllers/employees_controller.rb
require 'net/http'
require 'net/https'

class EmployeesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @employees = fetch_employees_from_api(params[:page])
  end

  def edit
    @employee = fetch_employee_from_api(params[:id])
  end

  def show
    @employee = fetch_employee_from_api(params[:id])
  end

  def create
    response = create_employee_via_api(employee_params)
    handle_response(response, :create)
  end

  def update
    response = update_employee_via_api(params[:id], employee_params)
    handle_response(response, :edit) 
  end

  private

  def handle_response(response, action)
    puts "Response Code: #{response.code}"
    puts "Response Body: #{response.body}"

    employee = JSON.parse(response.body)

    redirect_to action == :create ? employee_path(employee.dig("id")) : edit_employee_path(employee.dig("id"))
  end

  def employee_params
    {
      "name": params[:name],
      "position": params[:position],
      "date_of_birth": params[:date_of_birth],
      "salary": params[:salary]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <tr>
    <th scope="row"><%= blog.id %></th>
    <td><%= blog.title %></td>
    <td><%= blog.body %></td>
    <td><%= blog.user.email %></td>
    
    <% if blog.user == current_user %>
      <td><a href="<%= edit_blog_path(blog)%>" class="card-link">Edit</a></td>
    <% end %>
      <td><a href="<%= blog_path(blog)%>" class="card-link">Show</a></td>
  </tr>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog)  do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <%= form.text_field :title, class: 'form-control' %>
    
  </div>
  <div class="mb-3">
    <label for="body" class="form-label">Body</label>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <%= submit_tag "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="container" id="blogs">
<h1>Blogs</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Body</th>
      <th scope="col">User</th>
      <th colspan="2" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @blogs.each do |blog| %>
   <%= render blog %>  
  <% end %>
  </tbody>
</table>
<%== pagy_bootstrap_nav(@pagy) %>

</div>

app/views/blogs/new.html.erb
<div class="container">
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <h1 class="mt-5"><%= @blog.title %></h1>
  <p class="lead"><%= @blog.body %></p>

  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

</div>

app/views/employees/_edit_employee_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="editEmployee" tabindex="-1" aria-labelledby="editEmployeeLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editEmployeeLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
<h1>Editing Employee</h1>


<%= form_tag employee_path(@employee.dig("id")), :method => :put do %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= text_field_tag :name, @employee.dig("name"), class: 'form-control' %>
    
  </div>
  <div class="mb-3">
    <label for="position" class="form-label">Position</label>
    <%= text_field_tag :position, @employee.dig("position"), class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="salary" class="form-label">Salary</label>
    <%= number_field_tag :salary, @employee.dig("salary"), class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="date_of_birth" class="form-label">Date of Birth</label>
    <%= date_field_tag :date_of_birth, @employee.dig("date_of_birth"), class: 'form-control' %>
  </div>

  <%= submit_tag "Submit", class: 'btn btn-primary' %>
<% end %>

</div>
<br>

app/views/employees/index.html.erb
<div class="container">
  <h1>Employees</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Salary</th>
        <th scope="col">Position</th>
        <th scope="col">Date Of Birth</th>
        <th colspan="2" scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.dig("data").each do |e| %>
      <tr>
        <th scope="row"><%= e.dig("id") %></th>
        <td><%= e.dig("name") %></td>
        <td><%= e.dig("salary") %></td>
        <td><%= e.dig("position") %></td>
        <td><%= e.dig("date_of_birth") %></td>
        <td><%= link_to 'Edit', edit_employee_path(e["id"]) %> </td>
        <td><%= link_to 'Show', employee_path(e["id"]) %> </td>
  
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'First Page', employees_path(page: 1) %> |
  <%= link_to 'Next Page', employees_path(page: @employees.dig("meta","next_page")) %> |
  <%= link_to 'Previous Page', employees_path(page: @employees.dig("meta","prev_page")) %> |
  <%= link_to 'Last Page', employees_path(page: @employees.dig("meta","total_pages")) %>
</div>

app/views/employees/new.html.erb
<div class="container">
<h1>New Employee</h1>

<%= form_tag employees_path do %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= text_field_tag :name, nil,  class: 'form-control' %>
    
  </div>
  <div class="mb-3">
    <label for="position" class="form-label">Position</label>
    <%= text_field_tag :position, nil ,class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="salary" class="form-label">Salary</label>
    <%= number_field_tag :salary, nil,  class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="date_of_birth" class="form-label">Date of Birth</label>
    <%= date_field_tag :date_of_birth, nil, class: 'form-control' %>
  </div>

  <%= submit_tag "Submit", class: 'btn btn-primary' %>
<% end %>

  <%= link_to "Back", employees_path %>
</div>

<div>
</div>

app/views/employees/show.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <td><%= @employee.dig("name") %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= @employee.dig("position") %></td>
  </tr>
  <tr>
    <th>Salary</th>  
    <td><%= @employee.dig("salary") %></td>
  </tr>
  <tr>
    <th>Date of Birth</th>  
    <td><%= @employee.dig("date_of_birth") %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>"><img width="136" src="https://staunch.co/images/logo.svg"></a>

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= new_blog_path %>">New Blog</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal" aria-current="page" href="#">Import Blogs </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= employees_path %>">Employees</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= new_employee_path %>">New Employee</a>
        </li>

        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path, class: 'dropdown-item' %>
            </li>

            <!--<li><a class="dropdown-item" href="#">Another action</a></li>-->
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <% end %>
        <!--<li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>-->
      </ul>
      <!--<form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Import Blogs</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_tag("/blogs/import", :method => "post", :multipart => true) do %>
      <div class="modal-body">
          <%= file_field_tag 'attachment' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= submit_tag "Save", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>